# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1453410512);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1453410632);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453488063);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1453410152);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1453410392);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1453410752);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "NL");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151216120837");
user_pref("browser.slowStartup.averageTime", 1135);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "http://localhost:7001/console/console.portal?_nfpb=true&_pageLabel=CoreServerServerTablePage");
user_pref("browser.startup.homepage_override.buildID", "20151216120837");
user_pref("browser.startup.homepage_override.mstone", "38.5.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1,\"bookmarks\":0}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"addon-bar\",\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1448019999821");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1448019999821");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1447938125255");
user_pref("datareporting.policy.firstRunTime", "1447938064217");
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 543);
user_pref("datareporting.sessions.current.main", 71);
user_pref("datareporting.sessions.current.sessionRestored", 733);
user_pref("datareporting.sessions.current.startTime", "1453488574875");
user_pref("datareporting.sessions.current.totalTime", 29);
user_pref("datareporting.sessions.currentIndex", 13);
user_pref("datareporting.sessions.previous.10", "{\"s\":1453413515396,\"a\":8,\"t\":40,\"c\":true,\"m\":528,\"fp\":1623,\"sr\":2278}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1453487942883,\"a\":28,\"t\":200,\"c\":true,\"m\":231,\"fp\":858,\"sr\":1048}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1453488144667,\"a\":1,\"t\":2,\"c\":true,\"m\":71,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1453410031396,\"a\":57,\"t\":2106,\"c\":true,\"m\":246,\"fp\":1230,\"sr\":1355}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1453412139594,\"a\":34,\"t\":342,\"c\":true,\"m\":302,\"fp\":895,\"sr\":1137}");
user_pref("datareporting.sessions.prunedIndex", 7);
user_pref("dom.disable_open_during_load", false);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.5.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1453410513);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.5.0");
user_pref("extensions.lastPlatformVersion", "38.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.5.0\",\"st\":1453154247000,\"mt\":1450297667000}}}");
user_pref("gecko.buildID", "20151216120837");
user_pref("gecko.mstone", "38.5.0");
user_pref("idle.lastDailyNotification", 1453410724);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453410094);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20151216120837");
user_pref("media.gmp-manager.lastCheck", 1453410093);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1453410152);
user_pref("places.history.expiration.transient_current_max_pages", 96909);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.browser.homepage.disable_button.bookmark_page", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1453410724);
user_pref("toolkit.startup.last_success", 1453488574);
user_pref("toolkit.telemetry.previousBuildID", "20151216120837");
